### ISSUE TITLE
[1.12.2] Decrease Amount on Starvation value isn't working correctly.

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#100]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 4
AppleCore-mc1.12.2-3.4.0
jei_1.12.2-4.15.0.291
scalingfeast-1.6.1

-----

I have the value set at 6 for the Decrease Amount on Starvation config option and after taking enough starve damage... it only removes 1 point of max hunger.

**Comment by yeelp** [comment]
Hmm... Must be some oversight. I'll take a look into it

**Comment by yeelp** [comment]
This has been fixed in a recent commit (which I of course never wrote about to auto close this). SF 1.7 will have this fixed.
