### ISSUE TITLE
[Suggestion] Starve & Death Penalties to only lower max hunger if it was increased by Hearty Shanks and not by SoL: Carrot Edition Milestones & such.

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#104]
I have noticed that I lost max hunger that I've gained from Spice of Life: Carrot Edition which prob means that I will be unable to regain that lost hunger since I've already hit the food milestones. Would there be any possible way to only allow max hunger to drop if the player has eaten any of the Hearty Shanks?

Scaling Health does this where you can use X amount of it's Hearts to boost your max health up to a cap, if set, but if you die you can lose X Hearts upon respawning. All other health attributes are untouched.

**Example**
Say my max hunger is 20, and I have the Hearty Shank cap set to 40. You can gain +2 Max Hunger per Shank eaten so that brings me to 100 Max Hunger but now I can't gain any more Max Hunger from those shanks. I also gain +2 Max Hunger for each SoL Milestone so I do that 10 times and now my Max Hunger is 120.

Now... say I die or starve enough times and I lose enough Max Hunger... my Max Hunger would be capped at 40 since the SoL: Carrot Edition Milestone is uneffected but at this point I can once more eat Hearty Shanks up to 40 times to restore my Max Hunger back to 120.

One more thing to mention is that I think Hearty Shanks are a one time thing if you set a cap for them. I was wondering if those could work just like the Hearts from Scaling Health, being usable again if they were lost upon death or starving, if they were used beforehand.

**Comment by James103** [comment]
In other words, when you would normally lose max hunger, instead of directly subtracting from your max hunger, your Hearty Shank uses slowly get rolled back, which decreases your max hunger, but allows you to eat more Hearty Shanks to bring it back up.

**Comment by Z-Tunic** [comment]
Yup, exactly just how the Scaling Health Hearts work.

**Comment by yeelp** [comment]
It's been a while since I've looked at SF's codebase, but I can definitely see the problem here with losing max hunger you can't get back. I'll have to see how it's handled internally and go from there :+1:
