### ISSUE TITLE
[Suggestion] Bloated Text resize for the Advanced Display.

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#108]
![](https://cdn.discordapp.com/attachments/377171551155650560/884591978619240488/bloatedtext.PNG)
At the moment, the text size for the bloated text is the same as the ones from 'Simple' display. Would it be do-able to have the bloated text be the same size as the Hunger/Saturation text if on the 'Advanced' display?

**Comment by yeelp** [comment]
fixed/added in e9bd62b
