### ISSUE TITLE
Mosquito/Maggot

### ISSUE THREAD

**Issue by yeelp** [yeelp/Scaling-Feast#17]
Add a mob that directly attacks a player's hunger value. Amount of hunger lost depends on difficulty.

If the mob attacks you when at zero hunger, you are killed instantly.

Maybe drops Hearty Shank sometimes? This may require the mob the be kinda rare. It'd be better if it were at least uncommon. Could drop Iron Apples instead, not sure

**Comment by yeelp** [comment]
So the idea is a mosquito-maggot pair of mobs. The mosquito attacks, drains some hunger, then lays eggs at its spawn location. After a while, the eggs hatch into Maggots, which will eventually grow into Mosquitos (Maggots can attack on their own). These mobs will respect a separate mob cap to prevent overcrowding. These mobs must also spawn on grass blocks, like passive mobs (most likely anyway). The scale of this idea kind of exceeds my abilities at the moment.

**Comment by James103** [comment]
There would have to be a config option to enable/disable natural spawning of such a mob, as some players may not want it spawning naturally in their world. 

Additionally, such an idea could be expanded to other mobs on a configurable basis. This would allow, for example, Husks to deduct 1 food point from players every successful attack.

The food point loss could even be made dependent on the HP damage dealt, allowing, for example, Chaos Guardians to drain player's hunger just as fast as player's health. This can encourage players to get all the foods and automate eating the top tier foods before fighting the Chaos Guardian, as they **will** need every food point they can get.

**Comment by yeelp** [comment]
I did have plans to make this mob spawning configurable.

The idea of every mob being able to deduct hunger is an interesting one. Iron Stomach could reduce the about lost, and there can be a configurable slider to determine how much of a mob's attack damage affects the amount of hunger you lose. So having it set to 0.5 could cause mobs that deal 3 damage to remove one hunger from you per hit (since it will round down.) Of course we then add a blacklist for mobs that won't get this ability (creepers and skeletons could be pretty crazy if they could do this, for example)  It could also be cool to add a toggle so that getting attacked when at zero hunger could instantly kill you.

This should probably be a separate feature request from this one. There may be no point to this mob anymore if this idea pans out well.

**Comment by Z-Tunic** [comment]
I kinda wonder how this would play out when paired with Scaling Health's damage scaling. Unless it's a separate damage value that affects saturation/hunger directly in which scaling health wouldn't upscale the damage for that.

Say a Husk hit me for 4 damage, which is up scaled to 1000+ or so damage due to scaling health. Would some of that scaled damage be converted to damage towards hunger or would be be a separate value?

**Comment by yeelp** [comment]
My preliminary plan is when I player gets damaged, I can get the damage source, find how much damage is being inflicted, then use that to create a new damage source that affects hunger/saturation. So depending on how Scaling Health scales damage, it may be possible to make this configurable. So, you can choose if you receive hunger damage based on the mob's base damage or on the modified damage. I do like the idea of both options (scaling vs. fixed hunger damage) so it'd be nice to make them both possible.

**Comment by James103** [comment]
Note that not all of the feature suggestions have to be implemented into the mod itself to be useable. There's CraftTweaker, which in this case contains all the necessary ingredients to put together a script that makes taking damage cause you to lose food points. The only question is: How would you put together such a script?

**Comment by yeelp** [comment]
Hmm, I could make it easier by enabling some direct CraftTweaker support. My knowledge with ZenScript is limited, so I'm sure it's possible with CraftTweaker on it's own, but perhaps exposing some methods of my API to CraftTweaker could be useful for pack makers?

**Comment by yeelp** [comment]
Also this discussion seems to be getting off topic from what the original issue was about. I don't think Scaling Feast needs a mob like this. It's much better to have the hunger damage system be applied to whatever mobs the user wants, which solves a more general problem than this original idea does. I'm closing this issue.

If the CraftTweaker support is a good idea, a separate issue can be opened.
