### ISSUE TITLE
[Suggestion] - Texture Blueprint

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#18]
Version 1
![](https://cdn.discordapp.com/attachments/377171551155650560/695216778820714568/scalingfeasttexturemockupv1complete.png)

This kinda took awhile but in this image shows a blueprint of the texture overlaying such as Hunger Shanks & Saturation, as well as separating the white outline from being used alongside Saturation which is the marker for your Max Hunger.

To the left is the Texture Coloring Test for Hunger while to the Right is the Coloring Test for Saturation. The middle shows what value they're currently at while under the tests is when all overlays are shown in-game, including the white outline for your max hunger cap as well as exhaustion.

While the coloring for the Hunger & Saturation are off or meshes in, you are able to change the coloring for the overlays via hex values so one can change the coloring to their liking. These colors are just examples & suppose I was going for a food theme of how spicy it is where yellow is mild & red is hot, etc.

The extra stuff at the bottom is just some textures from vanilla hunger as well as appleskin's saturation texture & the white outline. The actual usable textures are on the lower left side inside the yellow outline of the image which are 1x1 scale so it should be usable by copying the image. Their resolution is 9x9 which is inside the black outline.

Note that the textures in here are slightly updated than ones you currently have.

-----

If the above image doesn't work out... I did another mock-up where the saturation & max hunger cap overlays are swapped.

Version 2
![](https://cdn.discordapp.com/attachments/377171551155650560/695216799637045299/scalingfeasttexturemockupv2complete.png)

With this one no worries of any kind of meshing although exhaustion may be covered up more than before.

Note that the textures in here are slightly updated than ones you currently have.

-----

Here's what they look like in-game. The texture resolutions matched up correctly so I was able to do this.
A is Version 1 | B is Version 2.
![](https://cdn.discordapp.com/attachments/377171551155650560/695224244950401105/scalingfeasthudtest.PNG)

For both HUDs. Hunger is 30/30 and is on Layer 2 while Saturation is on Layer 1. I'm leaning towards B. Version 2 but that's just me. I noticed during these tests that the Max Hunger Cap white outline is transparent.

=====

P.S.
Could there be a config option to show Scaling Feasts Extra Hunger Overlay over the vanilla texture if on the first row? Basically when on the first row... the extra hunger overlay shows instead of the vanilla texture. Right now it currently goes by...

Vanilla Hunger Overlay, Extra Hunger Overlay 1, Extra Hunger Overlay 2, etc.

If you have the Extra Hunger Overlay for the first row, it would be...

Extra Hunger Overlay 1, Extra Hunger Overlay 2, Extra Hunger Overlay 3, etc.

**Comment by yeelp** [comment]
This is awesome. Thanks! Personally, I'm leaning more towards version 1, as this more closely mimics the style of AppleSkin with drawing saturation, and that might feel more natural for some players.

But honestly the max cap overlay is a way better idea than what I was currently doing.

The other suggestions are good too. Lets see what I can do.

**Comment by Z-Tunic** [comment]
That's true, players are used to AppleSkin overlays with the way it draws Saturation. Was trying another style to see if it could work.

If you need the 'guielements.png' file. I can post it as it already has the updated textures in it. Version 1 textures unless you want Version 2 textures as well?

**Comment by yeelp** [comment]
Commit 21c839f has finalized the new textures I needed for drawing max hunger. Commit 3b5ebe6 updated the HUD to use the new textures while also implementing a tracker to decrease max hunger while starving. I'm sticking to the current style I have for drawing half shanks for extended hunger, and switching to the half shank texture you have when replacing the vanilla colour. The reason for this is if you look at your half shank texture for 51 hunger, for example, it's hard to see the colour of the shank that's underneath it (there's only two yellow pixels). You can see the updated textures [here](https://raw.githubusercontent.com/yeelp/Scaling-Feast/master/src/main/resources/assets/scalingfeast/textures/gui/guielements.png), which should hopefully help describe what I mean. The only thing left for this issue is the PS at the bottom, which I'm currently working on. Unless the updated textures you have include some changes to the shading of the original textures, I shouldn't need them.

That being said, The ability to swap styles between version 1 and 2 seems like an interesting idea. However, that's not something I'm going to focus on right now.

**Comment by yeelp** [comment]
Commit 937ffb5 finishes up all suggestions related to this issue. Thanks!

**Comment by Z-Tunic** [comment]
Ah, I see what you mean. It does look hard to see but that's actually because I had the half-shank vanilla texture there. The textures in mine had different white shading on them but I can update the current one you posted with the different shading on them.

I see the Hunger Shanks are going to use three texture types instead of two... unless that's not finished

**Comment by yeelp** [comment]
Lmao yeah I literally just closed this as I finished everything up. If you don't mind updating the current texture map I posted with the new shading, that'd be great.

But other than that, everything else related to this issue is done

**Comment by Z-Tunic** [comment]
Not at all. Give me a few minutes. I'll do one for Version 2 as well.

**Comment by Z-Tunic** [comment]
...and, done.

Version 1 - AppleSkin Style
![](https://cdn.discordapp.com/attachments/377171551155650560/695405280841695282/AppleSkinStyleTexture-V1.png)

Version 2 - Other Style
![](https://cdn.discordapp.com/attachments/377171551155650560/695405298017632296/OtherStyleTexture-V2.png)

In Version 1, only the shading was changed. Version 2 is with the shading changed & swapping the saturation & max hunger cap textures.

**Comment by yeelp** [comment]
That's great, thanks so much!

**Comment by Z-Tunic** [comment]
No problem. If by any chance something is off with them, I can take another attempt at it.
