### ISSUE TITLE
Moveable HUD Position & Size Scaling Suggestion.

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#19]
![](https://cdn.discordapp.com/attachments/377171551155650560/695500143402680320/scalingfeasthudtextres.PNG)

The current hud seems a bit odd to me but that's might be just me not being used to how the gui is scaled. With the Smooth Font mod you can avoid this but... let's take an attempt at this.

In the picture I show the default hud with it's Simple & Advanced options alongside the HUD Text used for Scaling Health.

I have scaled down the HUD size for Advanced to 1X and put the saturation value above the hunger counter. If possible... the Hunger value will use the usual color changes as it is currently but for saturation it's hud color will be yellow as long as you have any sort of saturation. If it hits 0... it becomes grey'd out, meaning that Hunger will now start dropping.

If going with Simple I wasn't sure what type of scaling to use so I used 1X & 2X. I dunno the default scaling being used but I assume it's 1.5X or something.

P.S.
If this is possible, could there be a way to move the HUD around via X & Y values for Hunger & Saturation Values if on ADVANCED? SIMPLE would perhaps use only the Hunger HUD Placement since saturation values are hidden when using that option.

Also just noticed this but the Max Hunger Cap outline renders on any layer. Could this be changed so it only shows when you are on the layer where the cap is at? For example...

Max Hunger is 58, which is 3 Layers. If Hunger is 18/58... you are on Layer 1 and no max hunger cap outline renders. If at 36/58 Hunger you're on Layer 2, no outline renders... but when you have 54/58 Hunger, you are on Layer 3 and at this point the Max Hunger Cap Outline will render on the second to last Hunger Shank, since 58 is your cap.

**Comment by yeelp** [comment]
These HUD changes are a really good idea. I like the changes to the placement of saturation, which makes the overall text more compact.

Currently, text is scaled at 75% of its current size. This seems to closely resemble the text for Scaling Health, although it could be moved down a little bit for the SIMPLE style. ADVANCED could do well at 50% size and rearranged as you described. I can also add some config options for the saturation colour, with the default being yellow and grey.

The idea behind always drawing the max outline was that it showed information on a player's "starvation tracker" which causes them to lose max hunger if they take too much starvation damage. Not drawing it if they aren't on the same layer, so to speak, means that they won't have that crucial information when they deplete their hunger bar. An interesting compromise would probably be to make the outline transparent if you aren't on the same layer, that way you can still see it, with some configuration option to tweak that transparency level. Either that or display this starvation information some other way.

Lastly, moving the HUD elements around through config options is definitely possible. A more important point of discussion would be whether or not the saturation text can be moved independently of the hunger text, or if they move together.

I can probably get started on some of these features either today or tomorrow

**Comment by Z-Tunic** [comment]
Ah, I didn't know it was linked to the starvation tracker. Transparent could be worth a try if not on the same layer.

...Or if you are starving, the Tracker can appear. Does it reset back to normal if you happen to gain Hunger Shanks?

Saturation Text moving independently could be an option, but up to you for that.

**Comment by yeelp** [comment]
The tracker is completely configurable. You can set it to reset after gaining hunger shanks (i.e. eating anything), only after eating a Hearty Shank, or not at all.

I'll take a look at both the transparency and making the outline show up when starving, and see which works best

**Comment by Z-Tunic** [comment]
I might've though of something for the starvation tracker... when hunger is empty... the saturation outline starts to appear again but colored red/dark red? Each time you take starve damage this will fill up more & more and... when 'full'... your max hunger will start decreasing. Lemme grab a mock-up image right quick.

**Comment by Z-Tunic** [comment]
![](https://cdn.discordapp.com/attachments/377171551155650560/695695832544182292/scalingfeaststarvetracker.PNG)

Something like this. Top is when you took your first starve damage & bottom is when you took 5 starve damage, since the config is set at 5. At that point starve damage will now start affecting max hunger. The red outline will clear once you've eaten something to restore lose hunger.
