### ISSUE TITLE
[Enhancement] Epicurean gaining of max hunger

### ISSUE THREAD

**Issue by Foreck1** [yeelp/Scaling-Feast#29]
Currently there's a lack of incentive in various food mods to try varying diets, both versions of Spice of Life solve this problem to a degree, but with this it could be so much more.

In short, if SF could hook onto mods like Spice of life, in that case players would have a clear goal and incentive to eating ALL the foods! The more variety you have in your diet, the more you can eat, and the more saturation you gain to stay in a fight. So instead of unlocking extra hunger eating an iron apple, this configurable option would allow modpack makers to track how many food items have been eaten and reward players with the same prize.

Specific features
-Ideally different milestone would reward different amounts of hunger (for example, each 5 new foods, then each 10, then for the last few ones a boost of 5 hunger bars)
-Blacklist for food items that don't count towards milestones
-Dynamic tooltip for not eaten, valid food (takes into consideration the blacklist above)

Additional context
I'm a dev for Rebirth of the Night and I think this would create much more interesting food mechanics in our pack, whose harder crop harvesting (serene season) lacks motivational goals.

**Comment by yeelp** [comment]
This is actually a really cool idea, and probably not that hard to implement. I've spent some time thinking about exact details, and this is what I thought of.

Much like you said, Scaling Feast can reward a player for eating different foods, à la Spice of Life: Carrot Edition. There can be a configurable blacklist, and a configurable list of pairs (m, r) where m is a milestone amount, and r is the max hunger awarded at that milestone, in half shanks. 

However, this only goes so far. It encourages players to seek new food items, but does nothing to encourage a varied diet. So, this is where Scaling Feast can hook onto Spice of Life. Scaling Feast can check a player's food history, and punish a player by decreasing a player's max hunger if their food history isn't varied enough. I can probably get crazy and even check different food groups added by Spice of Life as opposed to different food items (or potentially check both) to determine if a player should be punished. Modpack makers can extend the length of the food history in Spice of Life to set how varied a player's diet should be. This definitely gives the Food Book in Spice of Life a lot more use as tracking and managing hood history is now a lot more important.

Regarding tooltips, some small tooltips for food items that will contribute to a player's max hunger can be added. A far more interesting addition would be a tooltip that warns a player if eating a certain food item will decrease their max hunger.

Lastly, a configuration option to disable the 'max hunger increasing' effects of the Hearty Shank can prevent players from cheating the system.

I currently have version 1.2.0-beta planned for release tomorrow (see PR #27 and the current open milestone for progress). I can try to squeeze this in for that release, but should it not be done in time, I'll add it in after.

**Comment by yeelp** [comment]
Delayed 1.2.0-beta by a day, but this feature was successfully added into the latest release. CurseForge should receive the latest version today or tomorrow. If I missed some features, you can reopen this issue. otherwise, open a new issue if you encounter any bugs.
