### ISSUE TITLE
[1.12.2] Game Crashes when you hold food.

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#31]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 3
AppleCore-mc1.12.2-3.2.0
AppleSkin-mc1.12-1.0.9
jei_1.12.2-4.15.0.291
scalingfeast-1.2.0-beta

Crash Report:
https://pastebin.com/wUyRWre5

=====

Was going to eat something to restore my hunger, and then got met with a game crash.

P.S.
Saturation Value for ADVANCE info slightly cuts off by a few pixels.

**Comment by yeelp** [comment]
Welp, good for me. Should've buffed that one out in testing.

**Comment by yeelp** [comment]
Now that you can actually play the game, can you get a screen cap and show how the saturation info is getting cut off in a separate issue?
