### ISSUE TITLE
[1.12.2] Transparency config for the Max Hunger Outline doesn't appear to work.

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#38]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 3
AppleCore-mc1.12.2-3.2.0
jei_1.12.2-4.15.0.291
scalingfeast-1.2.6-beta

-----

I set it to 0.0, it's appears solid. Unless it's suppose to be 1.0 but it's still solid. With the default 0.5 it still appears solid.

This is for DEFAULT & CUSTOM.

**Comment by yeelp** [comment]
This must've slipped past my verification. I can take a look at this tomorrow

**Comment by yeelp** [comment]
The transparency only works when your max hunger is above 20 and your current hunger is not on the same 'layer' as your max hunger (i.e. if your max is 34, the transparency only shows when your actual hunger is less than 20.) Is it not working when these conditions are met?

**Comment by Z-Tunic** [comment]
Nope, my max hunger is higher than 20 and if it's not on the same layer the transparency still shows solid.

![](https://cdn.discordapp.com/attachments/377171551155650560/702260701581803581/maxhungeroutlinesolid.PNG)

The config is set to 0.5 and it still appears to be solid.

**Comment by yeelp** [comment]
Found the issue. Should be fixed now

**Comment by yeelp** [comment]
I'm going to have this bug fix added to 1.3.0 and released then
