### ISSUE TITLE
ADVANCED Info saturation gain for always edible foods

### ISSUE THREAD

**Issue by yeelp** [yeelp/Scaling-Feast#47]
Best described with an example. When at full hunger, holding something like a golden apple doesn't show how much saturation gets restored in spite of the fact that it is still edible and will restore saturation.

**Comment by border999** [comment]
I would also like to state that unless I die, my hud never shows what my saturation is at if it's over 1x the saturation

**Comment by yeelp** [comment]
That's interesting. Can you open a separate issue and provide some screenshots please?

**Comment by border999** [comment]
https://github.com/yeelp/Scaling-Feast/issues/48
