### ISSUE TITLE
Tab-completion and entity selectors do not work in /sf setExtended??? <player>

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#49]
**Mod Version**: 1.3.1
**Minecraft Version**: 1.12.2
**Loaded Mods**:
![image](https://user-images.githubusercontent.com/37945304/81984463-6f4e8180-95fa-11ea-81a2-88b604b3c9f2.png)
(this modlist also applies to #50 and #51)

**Describe the bug**
When using entity selectors in `/sf setExtended??? <player>`, it errors out with (for example) `Player @p doesn't exist` instead of resolving the selector (in this case, to the executor).

Additionally, tab-completion on the player name fails, with the game reporting the following error:
[crash-2020-05-14_15.46.48-server.txt](https://github.com/yeelp/Scaling-Feast/files/4630806/crash-2020-05-14_15.46.48-server.txt)
[crash-2020-05-14_15.46.30-server.txt](https://github.com/yeelp/Scaling-Feast/files/4630807/crash-2020-05-14_15.46.30-server.txt)

**Steps to Reproduce**
1. Type the command `/sf setExtendedMax `, but don't hit enter to execute it yet.
2. Hit tab. The game reports an error as above.
3. With the command still up, type `@p 128`.
4. Hit enter. The command `/sf setExtendedMax @p 128` will execute, and error out with `Player @p doesn't exist`.

**Expected behavior**

Tab-completion and entity selectors both work in `/sf setExtended??? <player>`.

**Comment by yeelp** [comment]
Right. So I was aware that entity selectors didn't work but just completely forgot to do anything about it. At the time, I was working under some false assumptions. The code for the commands is kinda of old and could really use some updating anyway. Thanks for bringing these issues to my attention!

I can get this ironed out for 1.3.2
