### ISSUE TITLE
/sf setExtended has outdated error messages

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#50]
**Mod Version**: 1.3.1
**Minecraft Version**: 1.12.2
**Loaded Mods**: (Reproducible with just Scaling Feast)

**Describe the bug**
`/sf setExtended???` only actually supports `setExtendedMax`, even though `setExtendedFood` and `setExtendedSat` is shown to be supported.

**Steps to Reproduce**
1. Type `/sf` and hit enter.
2. Output: `Usage: /scalingfeast <setExtendedFood|setExtendedMax|setExtendedSat> <player> [args]`
3. Type `/sf setExtendedFood PLAYER 100` and hit enter.
4. Output: `Usage: /scalingfeast <setExtendedFood|setExtendedMax|setExtendedSat> <player> [args]` (expected: `Success!`)
5. Type `/sf setExtendedMax PLAYER 100` and hit enter.
6. Output: `Success!`
7. Type `/sf setExtendedSat PLAYER 100` and hit enter.
8. Output: `Usage: /scalingfeast <setExtendedFood|setExtendedMax|setExtendedSat> <player> [args]` (expected: `Success!`)

**Expected behavior**
All of the three subcommands (`setExtendedMax`, `setExtendedFood`, and `setExtendedSat`) work properly.

**Comment by yeelp** [comment]
This is actually a **super old** remnant of alpha that I clearly didn't remove. Originally, Scaling Feast tracked a player's bonus hunger and saturation itself, before letting AppleCore handle it for me (which is a much better choice). As such I had included commands to manually set these values, to set a player's hunger level now, you should use AppleCore's /hunger command, which you can find some documentation about [here](https://github.com/squeek502/AppleCore/wiki/AppleCore-features). It doesn't seem like you can set saturation with AppleCore commands. If you can't, and it's really something you need, and there's no other mod that can provide it, then you can open a feature request here and I'll think about it.

Much like I mentioned in #49, this command needs a serious go-over. The main problem here is the error message is completely obsolete
