### ISSUE TITLE
[1.12.2] HUD Bug if in Third-Person View.

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#53]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 3
AppleCore-mc1.12.2-3.2.0
jei_1.12.2-4.15.0.291
scalingfeast-1.3.1

=====

![](https://cdn.discordapp.com/attachments/377171551155650560/712474012663676979/SFhudbugthirdperson.PNG)
When in Third-Person view, the Hunger HUD bugs out. Does not occur if in First-Person View.

**Comment by yeelp** [comment]
Hmm... I'll see if I can get this resolved for 1.3.2 which should release on the 27th. I'm not sure why Minecraft distinguishes first person view from third person view in such a way as to cause this.
