### ISSUE TITLE
[Suggestion] Configurable Saturation Cap?

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#54]
Saturation is tied to your max hunger value, meaning if you have 100 hunger... you can also have 100 Saturation, meaning you have 200 actual hunger, effectively doubling your hunger in a way.

I wonder if there could be a way to config the saturation to these examples. Saturation will never go above these values.

***Examples***
Saturation Scaling: MAX HUNGER
Saturation Cap: 0

Max Hunger: 20
Saturation Limit: 0

Max Hunger: 62
Saturation Limit: 0

Max Hunger: 100
Saturation Limit: 0

-----

Saturation Scaling: HALF MAX HUNGER
Saturation Cap: -1

Max Hunger: 20
Saturation Limit: 10

Max Hunger: 70
Saturation Limit: 35

Max Hunger: 100
Saturation Limit: 50

-----

Saturation Scaling: QUARTER MAX HUNGER
Saturation Cap: 16

Max Hunger: 20
Saturation Limit: 5

Max Hunger: 56
Saturation Limit: 14

Max Hunger: 100
Saturation Limit: 16

=====

Hopefully I explained this well. I dunno if there could also be a overflow of saturation to go slightly beyond the cap, unless the mod Saturation Overflow works with Scaling Feast. I'll give that a check right quick.

*Note*
Each time exhaustion builds up fully... it takes away 1 saturation/hunger so even if you had 0.8 saturation or something... it would be treated as 1 saturation.

*EDIT*
Apparently Saturation overflow does appear to work, but the hud values from scaling feast won't update to show the overflow. The same thing occurs when viewing the Debug Info via F3 when you have Appleskin installed with or without Scaling Feast.

**Comment by yeelp** [comment]
Saturation Overflow has had some history of not working well with AppleCore - which Scaling Feast uses, so I wouldn't necessarily count on it. If Saturation Overflow does works with AppleCore, then it *should* work out of the box with Scaling Feast.

As for the saturation scaling, seems like a pretty cool idea, not too hard to do either.

As for that final note, this is standard vanilla behaviour. 0.2 saturation is really just as valuable as 1 saturation. However if mob attacks reduce hunger by some amount (see #17) then this small amount of saturation isn't as valuable as a full saturation point (if some mob inflicts 0.6 points of saturation damage, you have an extra 'hit' with 3.6 saturation versus 3.0 saturation).

Just saw your edit when typing this. I'm pretty sure Saturation Overflow has it's own separate 'counter' to determine your extra saturation, which AppleCore won't pick up when getting the saturation values for a player. If I wanted to make sure that information is displayed to the player in the HUD, I'd probably have to look through Saturation Overflow's code and do it myself, and I'm not too sure how much I really want to do that.

**Comment by Z-Tunic** [comment]
While I did say HALF & QUARTER. I wonder if a percentage would work out better since you'll have more control over it.

MAX would be 1.0, HALF would be 0.5, QUARTER would be 0.25. -1 would mean no cap... well... at least capped until max hunger the saturation cap anyways.

**Comment by James103** [comment]
This would also need to change the saturation display text from "1.0" to "1.0/2.0" in cases where the max saturation is not equal to the current hunger level, where "1.0" is the current saturation and "2.0" is the max saturation.
