### ISSUE TITLE
[1.12.2] HUD Overlay won't show how much Saturation/Hunger you'll gain & crash when holding the Hearty feast.

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#55]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 3
AppleCore-mc1.12.2-3.2.0
jei_1.12.2-4.15.0.291
scalingfeast-1.3.2

-----

In previous versions, the HUD would show how much Saturation/Hunger you'll gain when holding food... however it seems that it's partially broken where it won't show how much you'll gain. To name a few items...

Hearty Shank, Golden Apple, Enchanted Golden Apple will show what you'll gain if you hold them in your hand.

Apples, Steak, Raw Beef, Baked Potato, Pumpkin Pie, Carrot, etc. won't show what you'll gain when holding them in your hand.

Also... game crashes when you hold the Hearty Feast in your hand.
https://pastebin.com/2kuqhxFt

**Comment by yeelp** [comment]
I just noticed the first part of this report myself. Commit 7b9ac42 fixes this problem.

The second part comes from me rewriting a bit of code thinking it would make it better, but instead breaking things. Awesome.

I'll make a 1.3.3 hotfix that should be released sometime tomorrow that addresses these problems.

**Comment by yeelp** [comment]
Forgot to mention this in the commit message, but commit 3fb5dbf fixes this issue.
