### ISSUE TITLE
"/sf setMax @p 500" prints the player's location and the world's name.

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#57]
Mod Version: 1.3.2
Minecraft Version: 1.12.2
Loaded Mods: (Reproducible with just Scaling Feast)

**Describe the bug**
Typing `/sf setMax @p 500` prints `Success! Set max for player EntityPlayerMP[...] to 500`. The information printed includes the player's name and location and the current world's name. Same for `/sf setSaturation @p 500`.

**Steps to Reproduce**
In a world with cheats enabled and the mod loaded, type `/sf setMax @p 500` and/or `/sf setSaturation @p 500`.

**Expected behavior**
Typing `/sf setMax @p 500` prints `Success! Set max for player [NAME] to 500`, where [NAME] is the player's name and not the `EntityPlayerMP[...]` string that includes the player's location and the world's name. Same for `/sf setSaturation @p 500`.

**Comment by yeelp** [comment]
Whoops! That's my bad. I should've passed the player name when building the localized message, not the player itself. Thanks for pointing this out.
