### ISSUE TITLE
[Suggestion] Gluttony should affect health restored from eating an Iron Apple

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#58]
**Mod Version**: 1.3.3
**Minecraft Version**: 1.12.2
**Loaded Mods**: (Reproducible with just Scaling Feast)

**Describe the bug**
Eating an (Enchanted) Iron Apple does not give you more health even when you have the Gluttony enchantment. Since Iron Apples are supposed to act like Golden Apples but in reverse, this is inconsistent.

**Steps to Reproduce**
1. Obtain any chestplate and a Iron Apple.
2. Enchant the chestplate with Gluttony level 3.
3. Have 10 HP or less. This allows the full effect of the Iron Apple to take place with Gluttony 3.
4. Eat the Iron Apple.
5. You should gain 2.5 * 4 = 10 HP, but you only get 4 HP as if you didn't have Gluttony.

**Expected behavior**
Having the Gluttony enchantment should increase the health you get for eating an Iron Apple, just like how it increases the hunger you get for eating a Golden Apple.

**Comment by yeelp** [comment]
This wasn't originally intended, but I can see how this would be a good change.
