### ISSUE TITLE
Idea: New effects that mess with a player's hunger (to complete the set)

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#62]
Here's the current table of health effects and their hunger analogues:

**Health**|**Hunger**|**Effect**
:-----:|:-----:|:-----:
Regeneration|Metabolism|Increases health/hunger over time
Poison/Wither|Hunger|Decreases health/hunger over time
Resistance|Iron Stomach|Decreases the rate of health/hunger loss
???|???|Increases the rate of health/hunger loss
Instant Health|Saturation|Massively increases health/hunger over time
Instant Damage|???|Massively decreases health/hunger over time
Health Boost|???|Increases max health/hunger
Absorption|???|Temporarily protects against health/hunger loss
[Malnourished](https://github.com/WesCook/Nutrition/wiki/New-Potion-Effects#malnourished)|???|Fine-tune decrease of max health/hunger
[Nourished](https://github.com/WesCook/Nutrition/wiki/New-Potion-Effects#nourished)|???|Fine-tune increase of max health/hunger

As you can see in the table, there are five gaps in the hunger table (actually 3 if you combine Health Boost with Nourished). The gaps are as follows:
* There's no status effect that massively decreases your hunger over time.
(There's Instant Damage which massively decreases your health over time) 
* There's no status effect that temporarily decreases max hunger.
(There's Malnourished from the Nutrition mod that temporarily decreases your max health)
* There's no status effect that temporarily increases max hunger.
(There's Health Boost and Nourished, which both temporarily increase your max health)
* There's no statis effect that increases the rate of health/hunger loss
(Negative levels aren't officially supported, but negative levels of Iron Stomach and Resistance theoretically would increase the rate of health/hunger loss)
* There's no status effect that provides temporary protection against hunger loss.
(There's Absorption which temporarily protects against health loss)

A complete analog set of health effects but for hunger should fill in all of these gaps. These new effects could be used anywhere to, for example, reward or punish players with changes to their max hunger based on their nutrition levels, health, or any other factor.

**Comment by yeelp** [comment]
TL;DR Cool idea. What do I name the effects, and what causes the effects? I doubt it'll make it into 1.4.0, but you can write a PR if you want some of the new potions effects in 1.4.0. Also, was Absorption excluded intentionally?

For the following, when I say a player's hunger, I'm referring to a player's food stats. So lowering a player's hunger would of course mean lowering the saturation first, then the hunger, if the saturation is depleted, as you would expect. With that said, a few notes:

The vanilla Hunger effect is a better candidate for the effect that increases the rate of exhaustion, see [here](https://minecraft.gamepedia.com/Hunger_(status_effect)#Effect). The poison/wither effect analogue should directly lower a player's hunger making it 'unblockable' by the Fasting enchant and Iron Stomach, similar to how Poison and Wither are unblockable by armor (Yes, Poison and Wither are blocked by Resistance, and maybe Iron Stomach can be tweaked to behave similarly, but that's not something to worry about right now). Thankfully, I've already written code that does exactly this in #60 (specifically [here](https://github.com/yeelp/Scaling-Feast/blob/fbfa4b0d09973921314358d7aaa549eed51d9745/src/main/java/yeelp/scalingfeast/util/HungerDamage.java)), so the mechanics are in place.

Another thing is obviously names. I only want potion names that ideally haven't been used before (names like Satiated are used by other mods, Famine is already an enchantment so I don't like that as a name). Perhaps Deficiency is a good name for the instant damage/poison analogue but I'm not entirely convinced.

There's also Absorption and I'm not sure if you excluded it intentionally or not. When I started writing this response, I initially didn't think it would be possible, but I now have an idea that could just maybe work.

While I like these ideas, a problem comes from causes. What in Scaling Feast can cause these effects? What items can be used as ingredients to brew these potions? If Absorption for hunger is developed, then that can be obtained through Iron Apples. But everything else has no instance where the player will encounter them. Yeah I can add new items, but I see no point in adding tons of items with no real purpose. Like, why would you want to craft/obtain an item that temporarily increases your max hunger when Hearty Shanks exist? I'm happy to add the effects, I'm just not sure where they'd be used.

This brings me to my last point. My todo list for 1.4.0 is a little on the long side, so I don't want to make any promises that these effects make it in to the next release. Feel free to write a PR for whichever ones you want most, and I can add the rest in after 1.4.0.

**Comment by James103** [comment]
Like you said, based on current development rates, I would like this to be implemented **after** 1.4.0.

I don't care if the hunger-analog effects have any causes at all. I only care if the hunger-analog effects exist and are functional. They don't need a survival-mode cause since there are other ways to get them (via commands, scripts, etc).

Until actual names are suggested and available for use in Scaling Feast, here are some tentative names for the additional status effects (listed in **bold**):
**Health**|**Hunger**|**Effect**
:-----:|:-----:|:-----:
Regeneration|Metabolism|Increases health/hunger over time
Poison/Wither|Hunger|Decreases health/hunger over time
Resistance|Iron Stomach|Decreases the rate of health/hunger loss
**Vulnerability**|(Super) **Hunger**|Increases the rate of health/hunger loss
Instant Health|Saturation|Massively increases health/hunger over time
Instant Damage|**Deficiency**|Massively decreases health/hunger over time
Health Boost|**Hunger Plus**|Increases max health/hunger
Absorption|**Saturated**|Temporarily protects against health/hunger loss
[Malnourished](https://github.com/WesCook/Nutrition/wiki/New-Potion-Effects#malnourished)|**Hunger Minus**|Fine-tune decrease of max health/hunger
[Nourished](https://github.com/WesCook/Nutrition/wiki/New-Potion-Effects#nourished)|**Hunger Plus**|Fine-tune increase of max health/hunger

**Comment by James103** [comment]
As for the icons, here are my suggestions:
* Vulnerability: A broken shield, inspired by the Resistance effect.
* Soft Stomach: The shape of Iron Stomach plus the texture of Rotten Flesh.

* Saturation (effect): A hunger icon with arrow pointing down.
* Deficiency: A hunger icon with arrow pointing up.
* Saturated: A fully yellow hunger icon(s).

* Hunger Plus: A saturation icon with arrow pointing up.
* Hunger Minus: A saturation icon with arrow pointing down.


As for the exact effects:
* Vulnerability: Increases HP damage taken by 20% per level.
* Soft Stomach: Increase food exhaustion rate by 20% per level.

* Deficiency: Instantly deducts the effect level in food points. If forced to last longer than 1 tick, deducts food points every tick. The rate of food point loss can go beyond 20 food points per second with higher levels of this effect.
* Saturated: Grants extra saturation that can go beyond the normal saturation cap. Any extra saturation provided by the effect is revoked when the effect ends. If you have saturation but no hunger while the effect is active, starvation doesn't take place. Caused by eating an Iron Apple or (perhaps) as a side effect of using the Totem of Undying to protect against starvation damage.

* Hunger Minus: Decreases max hunger by 1 per level, but can't go below a lower bound (0, 1, 20, or perhaps configurable).
* Hunger Plus: Increases max hunger by 1 per level, but can't go above the max hunger hard cap (default -1 == `Short.MAX_VALUE`).

**Comment by yeelp** [comment]
Actually, PotionCore adds a Vulnerability potion effect (Same name too) that decreases damage resistance by 50% per level. In addition, messing with health related effects seems out of the scope of Scaling Feast.

I won't be adding icons for instant acting potions, as the only way a player would see them would be if they used commands, so it seems a bit of a waste to me.

For Hunger Plus/Minus, I'll probably use a green/red saturation icon with the corresponding arrow to make them a little more distinct.

These are great starts to these icons though, I'll see what I can come up with using my more limited artistic abilities lol.

As for adding effects to the Totem of Undying, I'm not for it. If I'm adding the Saturated effect, then it would follow that I should add Metabolism to it as well. But now, if players are low on hunger with a totem with no food items, they are encouraged to quite literally kill themselves to gain hunger/prevent starvation. The totem should remain unchanged.

**Comment by James103** [comment]
> Like you said, based on current development rates, I would like this to be implemented after 1.4.0.

Here is my version of a future roadmap for this mod:
* Scaling Feast 1.4: I don't care about any more features making it there, just bug fixes as needed.
* Scaling Feast 1.5 should implement #62, #66, and #52, assuming they aren't implemented in 1.4.
* After that, would it be possible to port Scaling Feast to 1.15+?

**Comment by yeelp** [comment]
1.4 could contain #62, #66 and #52, as I'm ahead of schedule by over a week. #52 already exists mechanically in code, just commented out, and adding curse enchants and a few potion effects shouldn't take a lot of time.

Porting Scaling Feast to 1.15+ would be cool and definitely something I'll need to do at some point. However, AppleCore isn't available for 1.15 (yet, I think the dev is working on it). Obviously the 1.15 modding environment is drastically different the the 1.12 environment, and with that comes a lot of considerations and challenges (I need to look into Fabric vs. Forge and see which I should use, will probably just stick to Forge though, as I barely know what Fabric is).

It may be possible to port to 1.15+ without AppleCore. But that would be a challenge. It may be better to wait until AppleCore gets updated, at which point trying to devise any sort of projected completion date is out of the question. A possible Scaling Feast v1.6.0 build for 1.12.2 may be possible, depending on where AppleCore's development is at when 1.5.0 comes out (assuming I still need AppleCore for a 1.15+ port)

**Comment by James103** [comment]
A far future idea for after Scaling Feast is feature-complete: Have you ever thought of making a mod that is similar to Scaling Feast in the basic ideas and some features, but that is all based around the thirst mechanic from Tough As Nails?

Pair this far future idea with Scaling Feast and a few other mods, and suddenly you're able to go from having just 20 HP, 20 food points, and 20 thirst, all the way to being in the hundreds in all three.

**Comment by yeelp** [comment]
> A far future idea for after Scaling Feast is feature-complete: Have you ever thought of making a mod that is similar to Scaling Feast in the basic ideas and some features, but that is all based around the thirst mechanic from Tough As Nails?

I actually am developing a modpack that uses Tough as Nails and Scaling Feast so this idea has crossed my mind multiple times. The problem is TAN is dead, and there's plenty of other mods that add thirst. For this mod to have longevity outside of 1.12.2, I would ideally want to be able to port it to future versions. So initially I thought about recreating Tough as Nails, which I would call A ReCreated Tough As Nails (Or ARCTAN for short, I'm a huge nerd), which I can then port to 1.15+ and bring this 'scaling thirst' idea with it. That's currently as far as I toyed with that idea, as recreatin Tough as Nails seems like an idea no one would gravitate to unless there was a real reason to.

**Comment by James103** [comment]
> So initially I thought about recreating Tough as Nails, which I would call A ReCreated Tough As Nails (Or ARCTAN for short, I'm a huge nerd)

The licence for Tough as Nails is CC BY-**NC-ND** 4.0. The "NC-ND" part basically means you can't use any code from the original Tough as Nails in your recreation. In other words, you would have to remake Tough as Nails from scratch while also trying not to take code or ideas directly off of the original. This includes using the full name of Tough as Nails in your project.

**Comment by yeelp** [comment]
Interesting. I never actually looked that far into. Thanks for the info!

**Comment by James103** [comment]
As for licences and textures, sourcing assets from Tough as Nails is out of the question due to the CC BY-**NC-ND** 4.0 licence. But you could source some assets from the mod ["SchopCraft"](https://github.com/Schoperation/SchopCraft), more specifically the texture for the water droplet and canister.

Alternatively, here are my own draft textures for the thirst bar:
https://user-images.githubusercontent.com/37945304/83090444-68922680-a05e-11ea-9ba5-2eee014ebd61.png
(top row is normal, bottom is poisoned)

**Comment by yeelp** [comment]
My main concern was if using a blue = normal, green = poisoned system was okay or not.

If I recreate such a mod, would using the textures you provided be alright?
