### ISSUE TITLE
[Feature] Curse Enchants

### ISSUE THREAD

**Issue by yeelp** [yeelp/Scaling-Feast#66]
There's some features of the AppleCoreAPI I've wanted to mess with but never found a good chance to do so. This is a great opportunity. I don't want curses that do the opposite of enchantments in place, as that just ruins things. All curses would be treasure enchants, just like vanilla curses, and a config option to disable them from generating (Which would require a restart). Both curses I've thought of pair really nicely with the mechanics of #52.

Curse of Laziness: Halves a player's max exhaustion (4.0 -> 2.0). The ramifications are obvious.  Doesn't quite do the opposite of Fasting, as Fasting reduces exhaustion, but doesn't touch max exhaustion.

Curse of Deprivation (Tentative name): Doubles the rate at which a player takes starvation damage.

**Comment by James103** [comment]
Have you ever thought of a curse that makes it take longer for you to eat and drink, with better meals and drinks taking longer? For example, a very light meal (up to 2-3 food points) could be quicker to eat than normal, while a top tier food (restoring 20-26 food points) could take up to 15-20 seconds to eat.

Additionally, have you ever thought of a curse that makes it so if you eat something but you don't have enough room in the stomach to fit the full meal, not only do you lose out on part of the meal, but you <ins>also get a bad effect</ins>?

**Comment by yeelp** [comment]
The first curse is basically Spice of Life in a nutshell. The ability to restrict this "Spice of Life" effect to a curse seems interesting, but I think this curse is best left out.

I actually really love the second curse though. This is actually the perfect opportunity to use some of the new potion effects from #62. I'm thinking giving a player Soft Stomach when they over eat, with the intensity varying with the amount they overate, would be a cool punishment. It essentially means overeating can defeat the point of eating in the first place, which sounds cool.

**Comment by yeelp** [comment]
I'm actually going to add a config option to make the second curse you suggested a global effect or just a curse, for those who like the dynamic it provides. This will of course, prevent the curse from generating on chestplates (since it's pointless).

**Comment by James103** [comment]
> Curse of Laziness: Halves a player's max exhaustion
> Curse of Deprivation (Tentative name): Doubles the rate at which a player takes starvation damage.

Are these relative to the vanilla defaults (meaning that max exhaustion with Curse of Laziness is always 2.0 and starvation damage with Curse of Deprivation is always 40 ticks), or are they relative to the previous values set (meaning that if max exhaustion is set to 10 and starvation damage is set for every 20 ticks, then the two curses would set max exhaustion to 5 and starvation damage for every 10 ticks)?

**Comment by yeelp** [comment]
It will end up being relative to previous values set.
