### ISSUE TITLE
Metabolism doesn't respect saturation cap

### ISSUE THREAD

**Issue by yeelp** [yeelp/Scaling-Feast#69]
With saturation scaling on, or a saturation hard cap, Metabolism just ignores this and still gives saturation only being bounded by a player's food level.

**Comment by Z-Tunic** [comment]
While not related... this sorta gives an idea where you could allow an overflow of some sorts. If you have 19/20 saturation and you eat a food item that gives 6 saturation so you'll have 25/20 saturation. This would be a one-time thing so as long as you're at the max saturation cap you can't overflow your saturation.

It'll still respect the player's food level so it'll mainly be used when you halve/quarter saturation based on max hunger or use the saturation cap.

**Comment by yeelp** [comment]
This is basically Saturation Overflow in a nutshell. If anything, I would just add a way to get this saturation overflow value and add it to whatever is displayed in the HUD. The code is open source on GitLab, so this shouldn't be too complicated if I choose to do it.

**Comment by Z-Tunic** [comment]
Some more info to add for this issue. The Vanilla Potion Effect 'Saturation' can also bypass the cap or if other modded stuff grants saturation. To name a few...

-----

Biscuit of Totality from Botania:
Gives you roughly a 1 second Vanilla Saturation Effect which regens up to 20 Saturation/Hunger.

Saturation Potion from Potion Core:
Recovers Saturation & Hunger when drunk.

Life Leech Enchantment from Cyclic:
Restores Saturation/Hunger based on Mob Health when KO'd.

Saturation Potion from Cyclic:
This is a different type of Saturation Effect, grants a passive regen of both Saturation & Hunger overtime.

-----

Eating food-like items appears to set the saturation value back to whatever you have the max cap set at so maybe a check where if it's above the cap, set the value back to the max cap.

**Comment by yeelp** [comment]
Yeah what's happening here is when a food item is eaten, I cap player saturation. But, when foodstats are added (which does occur when a food item is eaten, but can also occur through things like potion effects (i.e. Metabolism)), I forget to cap player saturation. This is why eating a food item reverts it. Adding a quick check on the FoodStatsAdditionEvent and removing the check on the FoodEatenEvent (since it's probably redundant at this point) should solve the problem, I just haven't gotten around to it yet.
