### ISSUE TITLE
New attribute: scalingfeast.exhaustionRate

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#74]
For packmakers that want to use Scaling Feast as a way to modify a player's exhaustion rate based on the equipment they're wearing, there is currently no easy way to do that, aside from the enchantment "Fasting" (which only supports changing the exhaustion rate to a multiple of 1/5, a set that doesen't include the numbers required for all use cases). The HungerTweaker mod exposes various methods that allow editing the exhaustion rate of various actions, but there is currently no way to make it be on a per-player basis.

To change that, I propose a attribute, as follows:
* Attribute Name: `scalingfeast.exhaustionRate`
* Default: 1
* Range: 0.0 .. 2048
* What it does: All exhaustion gained is multiplied by this value. 1 represents normal exhaustion, less than 1 reduces exhaustion rate, and more than 1 increases exhaustion rate.

This attribute can be used for a variety of purposes, especially in armor and tools (some of which can increase your exhaustion rate or reduce it), but also in many other places as pack makers see fit. If this attribute is implemented, then the potion effects Iron Stomach and Soft Stomach should modify the attribute.

This is how the attribute would look like in-game as an example:
![image](https://user-images.githubusercontent.com/37945304/83255532-3bd13280-a176-11ea-8a41-4ce3e0061820.png)

**Comment by yeelp** [comment]
A nice idea. I'll need to look into the attribute system, since it's completely different from capabilities but it shouldn't be too bad.

**Comment by yeelp** [comment]
Posting this here to fish for some ideas.

So a small discovery. Attribute works perfectly as intended. However, here's a pickaxe with a +300% exhaustion rate modifier on it. 
![exhaustrate](https://user-images.githubusercontent.com/22644157/83798938-05fae500-a673-11ea-9d09-679e1cae4018.png)

The modifier text is blue since the modifier value itself it positive. This is hardcoded, so I can't change it as far as I'm aware.

Changing it to something like "-300% Exhaustion Resistance" would make it red, but that's hardly intuitive to understand, at least to me. Maybe that's a reasonable change? Internally, the attribute would work exactly the same, just the signs of all the number would flip, which sounds error prone.

**Comment by James103** [comment]
> The modifier text is blue since the modifier value itself it positive. This is hardcoded, so I can't change it as far as I'm aware.

I think this is an issue occurring in vanilla Minecraft code that is more easily exposed by using Forge and a custom mod to add such an attribute, such as exhaustion rate. Could you forward that to the Forge team to see if they can allow "lower is better" attributes to be specified as such, inverting the colors used for positive (blue -> red) and negative (red -> blue) modifiers for that attribute?

**Comment by yeelp** [comment]
I find it unlikely that they will patch this for 1.12.2 Forge as many people have simply decided to move on from 1.12.2 development-wise. It would be a nice feature to add for future versions however, so I'll still open an issue over there about it.

The better more general solution would probably be something like
```
public void setBeneficialTextFormatting(TextFormatting format)
```

Which takes a TextFormatting enum and applies it whenever beneficial modifier text is rendered. There'd be a separate method for negative modifiers to so you can do stuff like set negative colours to black and positive colours to green.

If they happen to patch this for 1.12.2 that'd be pretty cool. But in the more likely case where it's only added for future versions, I'll probably stick to the exhaustion resistance attribute instead. I can switch back to exhaustion rate when I port to the newer version that supports this.

**Comment by James103** [comment]
> Changing it to something like "-300% Exhaustion Resistance" would make it red, but that's hardly intuitive to understand, at least to me.

I have an alternate suggestion. Instead of "Exhaustion Rate" or "Exhaustion Resistance", my suggestion would be called "Food Efficiency" (tentative name).
* Attribute Name (if changed): `scalingfeast.foodEfficiency`
* Default: 1 (100%)
* Range: 0.0 .. 2048
* What it does: All exhaustion gained is divided by this value. For example, 200% Food Efficiency means exhaustion gained is divided by 2, while 25% Food Efficiency multiplies exhaustion gain by 4.
* Advantages over Exhaustion Rate: The inversion means that bad values (for example 0.25, formerly 4) are correctly marked as in red rather than in blue. Good values (such as 2.0, formerly 0.5) are also correctly marked in blue instead of in red.

**Comment by yeelp** [comment]
I'm going revert Iron Stomach back to older behaviour. Instead of altering this attribute, it'll affect the exhaustion rate separately, as currently, there is no level at which Iron Stomach blocks all incoming exhaustion when using division.
