### ISSUE TITLE
Effect durations for e.g. Bloating II are divided by 40 instead of 2.

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#75]
**Mod Version**: scalingfeast-1.5.0
**Minecraft Version**: 1.12.2
**Loaded Mods**: (Reproducible with just Scaling Feast)

**Describe the bug**
Effect durations for level 2 are divided by 20 compared to their intended values. For example: what is supposed to be "Bloated II (1:00)" is instead "Bloated II (0:03).

**Steps to Reproduce**
Using JEI or creative mode, take a look at the new potions added in version 1.5.0 of Scaling Feast, more specifically the level 2 versions.

**Expected behavior**
"Bloated II (1:00)" should remain as "Bloated II (1:00)" (coming from "Bloated I (2:00)") instead of having the effect duration divided by 20.

**Comment by yeelp** [comment]
So this was something I had noticed in development but I forgot to fix it clearly. Thanks for pointing this out.
