### ISSUE TITLE
The Deficiency potion does not do anything.

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#76]
**Mod Version**: scalingfeast-1.5.0
**Minecraft Version**: 1.12.2
**Loaded Mods**: (Reproducible with just Scaling Feast)

**Describe the bug**
The Deficiency **potion** does not do anything, regardless of your health, hunger, or saturation levels.

**Steps to Reproduce**
1. Obtain and use a Deficiency **potion**.

**Expected behavior**
The Deficiency **potion** applies the Deficiency **effect** and therefore drains your hunger.

**Additional context**
The Deficiency **effect** works as intended, deducting the proper amount of hunger.

**Comment by yeelp** [comment]
Interesting. Of course I never thought to check that the one instant effect potion works after seeing that all the other potions worked.
