### ISSUE TITLE
Log spam: "foodEfficiency:1.0" printed every tick while you walk/sprint.

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#80]
**Mod Version**: scalingfeast-1.5.0
**Minecraft Version**: 1.12.2
**Loaded Mods**: (Reproducible with just Scaling Feast)

**Describe the bug**
Log spam: "foodEfficiency:1.0" occurs regardless of if you have any modifiers affecting your food efficiency (such as a diamond shovel). Originates from here:
https://github.com/yeelp/Scaling-Feast/blob/a4560906fd6f9b9121fb7760b6a9fb9daaeee1f8/src/main/java/yeelp/scalingfeast/handlers/FoodHandler.java#L133

**Steps to Reproduce**
1. /give @p minecraft:diamond_chestplate 1 0 {AttributeModifiers:[{AttributeName:"scalingfeast.foodEfficiency",Name:"scalingfeast.foodEfficiency",Amount:1,Operation:2,UUIDLeast:629237,UUIDMost:992869,Slot:"chest"}]}

**Expected behavior**
No such log spam.

**Screenshots**
(It's just repeating the same line: `[09:43:38] [Server thread/INFO] [scalingfeast]: [SCALING FEAST] foodEfficiency:1.0`)
![image](https://user-images.githubusercontent.com/37945304/83947355-fea31b00-a7db-11ea-969c-a7512e04e5e6.png)

**Comment by yeelp** [comment]
Yup, I once again, left debug mode on when I released this, like I usually do. Already addressed this. Can get a release out for this in a couple days probably.
