### ISSUE TITLE
Hunger level can go above cap

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#82]
**Mod Version**: scalingfeast-1.5.0
**Minecraft Version**: 1.12.2
**Loaded Mods**: (Reproducible with just Scaling Feast)

**Describe the bug**
Hunger level can be greater than cap. Additionally, hunger level above cap is not shown in green.

**Steps to Reproduce**
1. `/sf setMax @p 500` and `/hunger 1`
2. `/give @p minecraft:stone 1 0 {AttributeModifiers:[{AttributeName:"scalingfeast.maxHungerMod",Name:"test",Amount:500,Operation:0,UUIDLeast:880424,UUIDMost:129850}]}`
3. Hold this stone in your hand (or equip it in your head slot).
4. `/effect @p saturation 2 500`
5. Take a look at your food level.

**Expected behavior**
Hunger level resets back to max when max hunger decreases.
![image](https://user-images.githubusercontent.com/37945304/83972363-56f21f80-a8a5-11ea-95df-325f17f2df2c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/37945304/83972351-480b6d00-a8a5-11ea-8d8c-c69ce20ab21e.png)

**Additional context**
Saturation can't go above cap, see 6743a8fa6734ba566c697204decbd7a1daf891dc

**Comment by yeelp** [comment]
Nice catch. Should be an easy fix.
