### ISSUE TITLE
No numerical values displayed next to Bloating effect hunger.

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#84]
**Mod Version**: 1.5.x
**Minecraft Version**: 1,12,2
**Loaded Mods**: (Reproducible with just Scaling Feast) 

**Describe the bug**
Even when the setting to display numerical values for hunger is enabled, no numerical values are displayed for the portion of the hunger bar caused by the Bloating effect.

**Steps to Reproduce**
1. Somehow obtain the Bloating effect.
2. Take a look at the HUD.

**Expected behavior**
When the setting to display numerical values for hunger is enabled, numerical values for Bloating are displayed next to the corresponding hunger bar as well. (At least the numerical value representing the current bloated hunger amount should be displayed, whether it be divided by 20 or not)

**Comment by yeelp** [comment]
Much like Minecraft with vanilla Absorption, Scaling Feast has no way of telling what a player's current 'maximum' bloated value is, it just knows how many bloated shanks a player currently has (this is a small part of why #78 isn't really fixable and more or less 'working as intended'). With no max to compare to, the best I could try to do would be the simple info approach of showing how many bars of Bloated hunger a player has.

**Comment by yeelp** [comment]
Forgot to mention in commit message, but commit d81b96bf6086e311045ad55a2840ea04bf015430 resolves this.
