### ISSUE TITLE
[Suggestion] Minimal amount of hunger restore needed for a food item to count towards increasing max hunger via Spice of Life: Carrot Editon.

### ISSUE THREAD

**Issue by Z-Tunic** [yeelp/Scaling-Feast#89]
Hopefully I can explain this right...

In Spice of Life: Carrot Edition, you can set a minimal amount of hunger that a food item needs to restore in order for it to count towards increasing your max health. I wonder if something like this could be done with increasing max hunger?

I am currently messing with Spice of Life: Carrot Edition's config for minimal hunger needed and it looks that it's shared for both increasing max health & hunger, although the amount that you need to eat is separated.

Now thinking about it... I wonder if this could also affect 'foodEfficiency' much like with max hunger? Like over-stuffing yourself with a lot of food will grant you a foodEfficiency bonus, like in this example...

100:0.05 -> Eating 100 kinds of food items will give you a +5% foodEfficiency.
200:0.1 -> Eating 200 kinds of food items will give you a +10% foodEfficiency, making it 15% Total.
400:0.2 -> Eating 400 kinds of food items will give you a +20% foodEfficiency, making it 35% Total.

**Comment by yeelp** [comment]
So you're wondering if the minimal hunger value can be separate from both SOL:Carrot and Scaling Feast's integration? I suppose yeah.

The foodEfficiency is interesting... it would have to be up to the player to ensure the configs don't make it busted. I'll have to see how things are implemented for COL:Carrot integration to see how much overhauling such an idea might need.

**Comment by Z-Tunic** [comment]
Yea, like in Scaling Feast's config you need to eat... say 15 food to increase max hunger where SOL:Carrot requires 10 food to increase max health.

The 'foodEfficiency' boost would be up to the player to ensure that they don't have it reach a high cap of some sorts, or to the point where hunger will no longer drain. I was going to give it a high food requirement in order to obtain the bonus.

**Comment by yeelp** [comment]
I'm looking into how I handled SOL:Carrot integration and I'm realizing having a custom minimal hunger value won't work unless I redo the entire food tracking system myself, at which point there's no need for SOL:Carrot in the first place, so I'll have to say that such a change isn't possible.

Also, no matter what food efficiency you have, you can never prevent your exhaustion from increasing. Food efficiency is a percentage change  i.e. a food efficiency of 200% means your exhaustion increases 200% slower than normal, **but it still increases**, so you could reasonably set the values to whatever you want.

I kind of forgot I did it like that, and I'm glad I did, as it prevents things from getting busted right out the gate. You can see a discussion of how it works in #81, if you're curious.
