### ISSUE TITLE
Hunger drains below Vanilla max

### ISSUE THREAD

**Issue by Minecr4ck** [yeelp/Scaling-Feast#90]
**Mod Version**: scalingfeast-1.5.3.jar
**Minecraft Version**: 1.12 forge-14.23.5.2854
**Loaded Mods**:  Too many to list. Will try to reproduce outside of modpack.

**Describe the bug**
Dying reduces hunger far below "vanilla maximum".  According to your config...

"death penalty" {
            # If not set to zero, this field indicates how much hunger you lose on death. Will not bring your respawning hunger value below vanilla's default maximum
            # Min: 0
            # Max: 32767
            I:"Hunger Lost on Death"=10

            # If not set to zero, this field indicates how much of your maximum hunger you lose upon death. Can not go below the default vanilla maximum.
            # Min: 0
            # Max: 32767
            I:"Max Lost on Death"=20
        }

With these settings, my hunger gets drained down to 1 shank.

**Steps to Reproduce**
Die repeatedly until hunger is lowered. Usually just 1-3 times from baseline vanilla max(depending on settings of course)
!

**Expected behavior**
I was expecting that hunger would stop being permanently reduced at 10 shanks(vanilla max)

**Screenshots**
![2020-09-22_08 18 13](https://user-images.githubusercontent.com/26249745/93887444-52af0e00-fcac-11ea-8ab6-b7d0199d89ae.png)

**Comment by Minecr4ck** [comment]
Tested with just Scaling Feast 1.5.3  and Applecore 3.4.0, same result.

![2020-09-22_08 56 26](https://user-images.githubusercontent.com/26249745/93892197-df0fff80-fcb1-11ea-8990-781aac49d3ce.png)

![2020-09-22_08 57 24](https://user-images.githubusercontent.com/26249745/93892203-e33c1d00-fcb1-11ea-8fdd-8549cb8975e3.png)

**Comment by yeelp** [comment]
Hmmm.... I wonder if capping it at the vanilla max was a paranoid precaution that I realized wasn't a problem and then simply ignored, and then forgot to change the config text. I'll add a configurable lower cap though, as that seems like a reasonable addition.

**Comment by Minecr4ck** [comment]
So what your saying is... 
If MAX HUNGER LOST ON DEATH is set to VANILLA MAX or higher(20+), then player will not lose health below that.
BUT because I had set it to lower than VANILLA MAX, then things go goofy and decided to ignore the lower cap? (in this case, 10)
