### ISSUE TITLE
1.12.2 Max Hunger Limit Reset after relog.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [yeelp/Scaling-Feast#97]
**Mod Version**: 1.6.1
**Minecraft Version**: 1.12.2
**Loaded Mods**: https://www.technicpack.net/modpack/pixelmon-evolved-zer0-edition.1763938
**Describe the bug**
During testing I noticed my default max health is reset back to 20.0 it was last left at 36.00

**Steps to Reproduce**
Run my pack through join server increase hunger and log off.

**Expected behavior**
Max Hunger remain through logging off and logging on.

**Screenshots**
Forget to get them.

**Additional context**
None so far. If you want to be modded on my server dev I can mod you for testing purposes.

**Comment by yeelp** [comment]
I'm guessing this only happens in multiplayer? I haven't ever had this happen to me in single player from what I remember. So I'm guessing this is a packet thing, but I'm fairly positive I've handled that correctly. Seems like I missed something.

The solution should be really easily to implement if I can find the exact cause of the issue. A few questions that could help, if you have the time:

- Does the max hunger gained from Hearty Shanks disappear?
- Does the max hunger gained from the /sf command disappear? (I believe it's something like /sf setMax or /sf setExtendedMax with arguments <player> and <amount>)
- Does max hunger gained/lost from Spice of Life (and SOL:Carrot) disappear?

If it's yes to all three, then that's an annoying problem to solve. If at least one of them stays on a relog, then that should help me a ton to find the problem.

**Comment by P3rf3ctXZer0** [comment]
* Does the max hunger gained from Hearty Shanks disappear? 

-- yes

* Does the max hunger gained from the /sf command disappear? (I believe it's something like /sf setMax or /sf setExtendedMax with arguments and )

-- not tested

* Does max hunger gained/lost from Spice of Life (and SOL:Carrot) disappear?

--- Will not test.


I will try the command thing now.

**Comment by P3rf3ctXZer0** [comment]
https://i.imgur.com/5J1KiZt.png

Before I log off.

**Comment by P3rf3ctXZer0** [comment]
Hm this time it saves ... the command keeps the data.

**Comment by P3rf3ctXZer0** [comment]
Reset Hunger now trying with shank.

![Mwt9lmB 1](https://user-images.githubusercontent.com/10351221/97381898-0bfa9800-1898-11eb-9fab-40a87321e2f8.png)

**Comment by P3rf3ctXZer0** [comment]
I ate some shanks 
![syKwnof 1](https://user-images.githubusercontent.com/10351221/97382007-59770500-1898-11eb-9bcb-797d919e8dc1.png)

**Comment by P3rf3ctXZer0** [comment]
Seems to be working fine now ... I wonder why :(

**Comment by Aeron216** [comment]
Old bug I know but I wanted to report that the same thing happed in mine server and never understood why. Maybe it's fine now.

**Comment by yeelp** [comment]
Since 1.6.1, I've actually redone the whole hunger system which changes the way it's saved. Because of this, in 1.8.2, encountering this bug is likely impossible (although never say never haha), so make sure you're using a 1.8.0+ version (just be aware of the stats you'll lose in the transition, you can check the changelog on CurseForge for info) :+1:

**Comment by P3rf3ctXZer0** [comment]
Thanks I will keep this in mind.
