### ISSUE TITLE
scalingfeast-1.6.1 server spam about Spice of Life carrot edition and I disabled that module

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [yeelp/Scaling-Feast#98]
**Mod Version**: scalingfeast-1.6.1
**Minecraft Version**: 1.12.2
**Loaded Mods**: https://www.technicpack.net/modpack/pixelmon-evolved-zer0-edition.1763938

**Describe the bug**
Server spam - [16:16:51] [Server thread/ERROR] [scalingfeast]: [SCALING FEAST] [yeelp.scalingfeast.helpers.SOLCarrotHelper.getCountableFoodListLength(SOLCarrotHelper.java:118), yeelp.scalingfeast.handlers.ModuleHandler.start(ModuleHandler.java:71), net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1453_ModuleHandler_start_Start.invoke(.dynamic), net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90), net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182), net.minecraftforge.event.ForgeEventFactory.onItemUseStart(ForgeEventFactory.java:377), net.minecraft.entity.EntityLivingBase.func_184598_c(EntityLivingBase.java:2704), lance5057.tDefense.core.tools.bases.Shield.func_77659_a(Shield.java:62), net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217), net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358), net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765), net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32), net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9), net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13), java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source), java.util.concurrent.FutureTask.run(Unknown Source), net.minecraft.util.Util.func_181617_a(SourceFile:46), net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723), net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397), net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526), java.lang.Thread.run(Unknown Source)]

**Steps to Reproduce**
Meh

**Expected behavior**
A feature I have disabled should be disabled.

**Screenshots**

**Additional context**
https://gist.github.com/P3rf3ctXZer0/2a1a49ecff38883f3d7bda7622556a86

**Comment by yeelp** [comment]
This has been fixed in 1.7, which should be released in around a week.
